const ProjectsData = [
  {
    id: 1,
    title: "Project 1",
    description: "This is a project description",
    image: "https://via.placeholder.com/300",
    githubLink: "https://www.google.com",
    liveLink: "https://www.google.com",
    techStack: ["React", "Node", "Express"],
  },
  {
    id: 2,
    title: "Project 2",
    description: "This is a project description",
    image: "https://via.placeholder.com/300",
    githubLink: "https://www.google.com",
    liveLink: "https://www.google.com",
    techStack: ["React", "Node", "Express"],
  },
  {
    id: 3,
    title: "Project 3",
    description: "This is a project description",
    image: "https://via.placeholder.com/300",
    githubLink: "https://www.google.com",
    liveLink: "https://www.google.com",
    techStack: ["React", "Node", "Express"],
  },
  {
    id: 4,
    title: "Project 4",
    description: "This is a project description",
    image: "https://via.placeholder.com/300",
    githubLink: "https://www.google.com",
    liveLink: "https://www.google.com",
    techStack: ["React", "Node", "Express"],
  },
  {
    id: 5,
    title: "Project 5",
    description: "This is a project description",
    image: "https://via.placeholder.com/300",
    githubLink: "https://www.google.com",
    liveLink: "https://www.google.com",
    techStack: ["React", "Node", "Express"],
  },
  {
    id: 6,
    title: "Project 6",
    description: "This is a project description",
    image: "https://via.placeholder.com/300",
    githubLink: "https://www.google.com",
    liveLink: "https://www.google.com",
    techStack: ["React", "Node", "Express"],
  },
  {
    id: 7,
    title: "Project 7",
    description: "This is a project description",
    image: "https://via.placeholder.com/300",
    githubLink: "https://www.google.com",
    liveLink: "https://www.google.com",
    techStack: ["React", "Node", "Express"],
  },
  {
    id: 8,
    title: "Project 8",
    description: "This is a project description",
    image: "https://via.placeholder.com/300",
    githubLink: "https://www.google.com",
    liveLink: "https://www.google.com",
    techStack: ["React", "Node", "Express"],
  },
];

export default ProjectsData;
